pipiline
{
agent any
stages{

    stage('Build')
    {
        steps {
            echo "This is build stage"
        }
    }

    stage('TEST')
    {
        steps {
            echo "This is test stage"
        }
     }
       stage('Deploy')
    {
        steps {
            echo "This is deploy stage"
        }
     }
    }
}
